### ISSUE TITLE
Program to convert wav to header (.h) file?

### ISSUE THREAD

**Issue by pedro-javierf** [GregAC/pico-stuff#1]
Hi, which software have you used to convert .wav samples to .h?
I've seen it is just a dump of all the samples into an array so shouldn't be difficult to program that, but I wanted to ask in case there is some already available tool to do it easily.

**Comment by GregAC** [comment]
Hi @pedro-javierf, apologies only just seen this issue.

I used audacity, it has a raw output option (see https://manual.audacityteam.org/man/other_uncompressed_files_export_options.html) which can give you just the samples in a variety of formats without a header (I used the 'unsigned 8-bit PCM encoding'). I then used a very crude python program to dump out the bytes with a little bit of formatting so it could be used as an initializer in C. Here's the code:

```python
audio_file = open('rock.raw', 'rb')

audio_bytes = audio_file.read()

for b in audio_bytes:
  int_b = int(b)
  print(f'{b},')
```
