### ISSUE TITLE
pwm_dma_led_fade: blog code works, but bug in GitHub code

### ISSUE THREAD

**Issue by gigamegawatts** [GregAC/pico-stuff#2]
Hi,

When I tried the pwm_dma_led_fade code, the LED didn't light.  The problem is that one line of the GitHub code doesn't match the code in the blog:

      fade[i] = 128 * 128;

... should be:

    fade[i] = (i * i) << 16;

Thanks for writing the blog entries, by the way.   It's the best source of information on the Pico DMA that I can find.

Dan.

**Comment by GregAC** [comment]
Thanks for letting me know @gigamegawatts think that was something I did for debugging and failed to fix in the repository.

Glad to hear the blog has been helpful.
